:markup-in-source: verbatim,attributes,quotes

== Create an Admin User for Cluster Access

If you want to be able to access your cluster immediately through a cluster-admin user, you can follow these steps.

This is good if you need quick access to the cluster, which is great for this workshop.

Though the recommended approach is to use a formal identity provider to access the cluster (and then grant that user admin privileges, if desired).

. Run this command to create the admin user
+
[source,sh,role=execute]
----
rosa create admin --cluster rosa-${GUID} -o yaml > cluster_admin.yaml
----

. Save an environment variable for your admin password and api server:
+
[source,sh,role=execute]
----
export ADMIN_PASSWORD=$(cat cluster_admin.yaml | grep password | awk '{print $2}')
echo "export ADMIN_PASSWORD=${ADMIN_PASSWORD}" >>$HOME/.bashrc

export API_SERVER=$(rosa describe cluster --cluster rosa-${GUID} -o json  | jq -r .api.url)
echo "export API_SERVER=${API_SERVER}" >>$HOME/.bashrc
----

[NOTE]
====
You will need to wait for a minute or two whilst the cluster-admin account is created on the ROSA cluser.
====

[start=3]
. Login to the ROSA cluster with your cluster-admin credentials
+
[source,sh,role=execute]
----
oc login $API_SERVER --username cluster-admin --password $ADMIN_PASSWORD --insecure-skip-tls-verify=true
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 101 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
+
[TIP]
====
If you get an error that the *Login failed (401 Unauthorized)* wait a few seconds and then try again. It takes a few minutes for the cluster authentication operator to update itself after creating the cluster admin user.
====

. To check that you are logged in as the admin user you can run `oc whoami`:
+
[source,sh,role=execute]
----
oc whoami
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
cluster-admin
----

. You can also confirm by running the following command. Only a cluster-admin user can run this without errors.
// +
// Also these pods may not yet exist or be in `Pending` status depending on how long it's been since your control plane finished installing.
+
[source,sh,role=execute]
----
oc get pod -n openshift-ingress
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
NAME                              READY   STATUS    RESTARTS   AGE
router-default-7994f6fd58-8cl45   1/1     Running   0          102s
router-default-7994f6fd58-z6gpm   1/1     Running   0          102s
----

. You can now use the cluster as an admin user, which will suffice for this workshop. Though, for any other use, it is highly recommended to set up an IdP.

// === Wait for Cluster Operators to finish rolling out

// Once your cluster has worker nodes available the cluster operators can deploy their operands to these worker nodes. These include the console and ingress controllers for example. Without those it will be impossible to access the cluster.

// . Repeat the following command every few minutes until the output looks like the example below (all operators should show as available, not progressing and certainly not degraded):
// +
// [source,sh,role=execute]
// ----
// oc get co
// ----
// +
// .Sample Output
// [source,texinfo,options=nowrap]
// ----
// NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
// console                                    4.12.18   True        False         False      2m41s
// csi-snapshot-controller                    4.12.18   True        False         False      16m
// dns                                        4.12.18   True        False         False      5m30s
// image-registry                             4.12.18   True        False         False      4m51s
// ingress                                    4.12.18   True        False         False      4m56s
// insights                                   4.12.18   True        False         False      6m8s
// kube-apiserver                             4.12.18   True        False         False      16m
// kube-controller-manager                    4.12.18   True        False         False      16m
// kube-scheduler                             4.12.18   True        False         False      16m
// kube-storage-version-migrator              4.12.18   True        False         False      6m3s
// monitoring                                 4.12.18   True        False         False      3m40s
// network                                    4.12.18   True        False         False      16m
// node-tuning                                4.12.18   True        False         False      6m37s
// openshift-apiserver                        4.12.18   True        False         False      16m
// openshift-controller-manager               4.12.18   True        False         False      16m
// openshift-samples                          4.12.18   True        False         False      5m6s
// operator-lifecycle-manager                 4.12.18   True        False         False      16m
// operator-lifecycle-manager-catalog         4.12.18   True        False         False      16m
// operator-lifecycle-manager-packageserver   4.12.18   True        False         False      16m
// service-ca                                 4.12.18   True        False         False      6m5s
// storage                                    4.12.18   True        False         False      6m27s
// ----

=== Login to the OpenShift Web Console

Next, let's log in to the OpenShift Web Console. To do so, follow the below steps:

. First, we'll need to grab your cluster's web console URL. To do so, run the following command:
+
[source,sh,role=execute]
----
oc whoami --show-console
----
+
.Sample Output
[source,text,options=nowrap]
----
https://console-openshift-console.%rosa_subdomain_base%
----

. Next, open the printed URL in a web browser.
//. Click on the `htpasswd` identity provider.
. Enter the username (`cluster-admin`) and password from the previous section (use `echo ${ADMIN_PASSWORD}` to remind yourself what the password is in case you forgot).
+
If you don't see an error, congratulations! You're now logged into the cluster and ready to move on to the workshop content.
